#!/usr/bin/env python3
"""
🚀 OppGrid Comprehensive Testing Report
Generated by RocketMan 🎯
"""

import os
import sys
import json
import subprocess
from pathlib import Path

def test_backend():
    """Test backend components"""
    print("🔍 BACKEND TESTING")
    print("=" * 60)
    
    os.chdir('/home/ldixon7584403/clawd-workspace/projects/Project-Spark/backend')
    
    issues = []
    warnings = []
    
    # Test 1: Python environment
    print("1. Python Environment:")
    print(f"   Version: {sys.version}")
    print(f"   Working dir: {os.getcwd()}")
    
    # Test 2: Core dependencies
    print("\n2. Dependency Analysis:")
    core_deps = ['fastapi', 'sqlalchemy', 'psycopg2', 'pydantic', 'anthropic', 'openai']
    for dep in core_deps:
        try:
            __import__(dep)
            print(f"   ✅ {dep}")
        except ImportError:
            print(f"   ❌ {dep} - MISSING")
            issues.append(f"Missing dependency: {dep}")
    
    # Test 3: App structure
    print("\n3. Application Structure:")
    required_files = [
        'app/main.py',
        'app/db/database.py', 
        'app/routers',
        'app/models',
        'app/services'
    ]
    
    for file_path in required_files:
        if os.path.exists(file_path):
            print(f"   ✅ {file_path}")
        else:
            print(f"   ❌ {file_path} - NOT FOUND")
            issues.append(f"Missing file: {file_path}")
    
    # Test 4: AI Services
    print("\n4. AI Services Status:")
    ai_services = [
        'app/services/ai_orchestrator.py',
        'app/services/ai_router.py',
        'app/services/ai_cofounder.py',
        'app/services/ai_engine.py'
    ]
    
    for service in ai_services:
        if os.path.exists(service):
            print(f"   ✅ {service}")
        else:
            print(f"   ❌ {service} - NOT FOUND")
            issues.append(f"Missing AI service: {service}")
    
    # Test 5: Database models
    print("\n5. Database Models:")
    model_files = [
        'app/models/opportunity.py',
        'app/models/user.py',
        'app/models/scraped_source.py'
    ]
    
    for model in model_files:
        if os.path.exists(model):
            print(f"   ✅ {model}")
        else:
            print(f"   ❌ {model} - NOT FOUND")
            issues.append(f"Missing model: {model}")
    
    return issues, warnings

def test_frontend():
    """Test frontend components"""
    print("\n🔍 FRONTEND TESTING")
    print("=" * 60)
    
    os.chdir('/home/ldixon7584403/clawd-workspace/projects/Project-Spark/frontend')
    
    issues = []
    warnings = []
    
    # Test 1: Package.json
    print("1. Frontend Configuration:")
    if os.path.exists('package.json'):
        with open('package.json', 'r') as f:
            pkg_data = json.load(f)
        print(f"   ✅ package.json found")
        print(f"   Name: {pkg_data.get('name', 'N/A')}")
        print(f"   Version: {pkg_data.get('version', 'N/A')}")
    else:
        print("   ❌ package.json missing")
        issues.append("Missing package.json")
    
    # Test 2: Core dependencies
    print("\n2. Frontend Dependencies:")
    core_frontend_deps = ['react', 'react-dom', 'axios', 'react-router-dom']
    
    # Check node_modules (basic check)
    node_modules_exists = os.path.exists('node_modules')
    if node_modules_exists:
        print("   ✅ node_modules directory exists")
    else:
        print("   ⚠️  node_modules missing - run npm install")
        warnings.append("node_modules missing")
    
    # Test 3: Source structure
    print("\n3. Source Structure:")
    frontend_files = [
        'src/App.tsx',
        'src/main.tsx',
        'src/components',
        'src/pages',
        'src/hooks'
    ]
    
    for file_path in frontend_files:
        if os.path.exists(file_path):
            print(f"   ✅ {file_path}")
        else:
            print(f"   ❌ {file_path} - NOT FOUND")
            issues.append(f"Missing frontend file: {file_path}")
    
    # Test 4: Build configuration
    print("\n4. Build Configuration:")
    build_files = ['vite.config.ts', 'tsconfig.json']
    
    for build_file in build_files:
        if os.path.exists(build_file):
            print(f"   ✅ {build_file}")
        else:
            print(f"   ❌ {build_file} - NOT FOUND")
            issues.append(f"Missing build config: {build_file}")
    
    return issues, warnings

def test_ai_integration():
    """Test AI integration components"""
    print("\n🔍 AI INTEGRATION TESTING")
    print("=" * 60)
    
    os.chdir('/home/ldixon7584403/clawd-workspace/projects/Project-Spark/backend')
    
    issues = []
    warnings = []
    
    print("1. AI Service Files:")
    ai_files = [
        'app/services/ai_orchestrator.py',
        'app/services/ai_router.py',
        'app/services/ai_cofounder.py',
        'app/services/ai_engine.py',
        'app/services/ai_analysis.py'
    ]
    
    for ai_file in ai_files:
        if os.path.exists(ai_file):
            # Basic syntax check
            try:
                with open(ai_file, 'r') as f:
                    compile(f.read(), ai_file, 'exec')
                print(f"   ✅ {ai_file} (syntax OK)")
            except SyntaxError as e:
                print(f"   ❌ {ai_file} - SYNTAX ERROR: {e}")
                issues.append(f"Syntax error in {ai_file}: {e}")
        else:
            print(f"   ❌ {ai_file} - NOT FOUND")
            issues.append(f"Missing AI file: {ai_file}")
    
    print("\n2. AI Router Endpoints:")
    ai_routers = [
        'app/routers/ai_cofounder.py',
        'app/routers/ai_analysis.py',
        'app/routers/ai_chat.py',
        'app/routers/ai_engine.py'
    ]
    
    for router in ai_routers:
        if os.path.exists(router):
            print(f"   ✅ {router}")
        else:
            print(f"   ❌ {router} - NOT FOUND")
            issues.append(f"Missing AI router: {router}")
    
    return issues, warnings

def test_database():
    """Test database connectivity and structure"""
    print("\n🔍 DATABASE TESTING")
    print("=" * 60)
    
    os.chdir('/home/ldixon7584403/clawd-workspace/projects/Project-Spark/backend')
    
    issues = []
    warnings = []
    
    print("1. Database Configuration:")
    
    # Check for .env file
    if os.path.exists('.env'):
        print("   ✅ .env file exists")
        with open('.env', 'r') as f:
            env_content = f.read()
            if 'DATABASE_URL' in env_content:
                print("   ✅ DATABASE_URL configured")
            else:
                print("   ⚠️  DATABASE_URL not found in .env")
                warnings.append("DATABASE_URL missing from .env")
    else:
        print("   ⚠️  .env file missing")
        warnings.append("Missing .env file")
    
    print("\n2. Database Migrations:")
    if os.path.exists('alembic'):
        print("   ✅ Alembic migrations directory exists")
        
        # Count migration files
        migration_files = [f for f in os.listdir('alembic/versions') if f.endswith('.py')]
        print(f"   ✅ {len(migration_files)} migration files found")
    else:
        print("   ❌ Alembic directory missing")
        issues.append("Missing Alembic migrations")
    
    return issues, warnings

def main():
    """Run comprehensive tests"""
    print("🚀 OPPGRID COMPREHENSIVE TESTING REPORT")
    print("=" * 80)
    print("Generated by RocketMan 🎯")
    print("=" * 80)
    
    all_issues = []
    all_warnings = []
    
    # Run all tests
    backend_issues, backend_warnings = test_backend()
    frontend_issues, frontend_warnings = test_frontend()
    ai_issues, ai_warnings = test_ai_integration()
    db_issues, db_warnings = test_database()
    
    all_issues.extend(backend_issues + frontend_issues + ai_issues + db_issues)
    all_warnings.extend(backend_warnings + frontend_warnings + ai_warnings + db_warnings)
    
    # Summary
    print("\n" + "=" * 80)
    print("📊 TEST SUMMARY")
    print("=" * 80)
    
    print(f"🔴 CRITICAL ISSUES: {len([i for i in all_issues if 'CRITICAL' in i])}")
    print(f"❌ ERRORS: {len([i for i in all_issues if 'CRITICAL' not in i])}")
    print(f"⚠️  WARNINGS: {len(all_warnings)}")
    
    if all_issues:
        print("\n🔴 CRITICAL ISSUES TO FIX:")
        for issue in all_issues[:10]:  # Show first 10
            print(f"   • {issue}")
        if len(all_issues) > 10:
            print(f"   ... and {len(all_issues) - 10} more issues")
    
    if all_warnings:
        print("\n⚠️  WARNINGS TO ADDRESS:")
        for warning in all_warnings[:5]:  # Show first 5
            print(f"   • {warning}")
        if len(all_warnings) > 5:
            print(f"   ... and {len(all_warnings) - 5} more warnings")
    
    print("\n" + "=" * 80)
    print("🎯 RECOMMENDATIONS:")
    print("=" * 80)
    print("1. Install missing Python dependencies: fastapi, sqlalchemy, anthropic, openai")
    print("2. Set up virtual environment for backend")
    print("3. Install frontend dependencies: npm install")
    print("4. Configure database connection in .env file")
    print("5. Run database migrations: alembic upgrade head")
    print("6. Test backend startup: uvicorn app.main:app --reload")
    print("7. Test frontend build: npm run build")
    
    print("\n🚀 Ready to proceed with fixes!")

if __name__ == "__main__":
    main()